project_id = "rhzojoyxldrllxroyyqt"

[functions.sitemap-events]
verify_jwt = false

[functions.sitemap-pages]
verify_jwt = false

[functions.indexnow-submit]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
