project_id = "rhzojoyxldrllxroyyqt"

[functions.fetch-ticketmaster]
verify_jwt = false

[functions.scrape-shotgun]
verify_jwt = false

[functions.refresh-events]
verify_jwt = false

[functions.fetch-eventbrite]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false
