project_id = "rhzojoyxldrllxroyyqt"

[functions.fetch-ticketmaster]
verify_jwt = false

[functions.scrape-shotgun]
verify_jwt = false

[functions.refresh-events]
verify_jwt = false

[functions.fetch-eventbrite]
verify_jwt = false

[functions.fetch-meetup]
verify_jwt = false

[functions.fetch-infoconcert]
verify_jwt = false
