// Runs before `vite dev` and `vite build` (predev/prebuild hooks).
// Writes a 3-tier sitemap index + one urlset per tier so Googlebot crawls
// the highest-priority URLs first.
//
// Outputs:
//   public/sitemap.xml           — sitemap index (references the 3 tiers + events)
//   public/sitemap-tier1.xml     — grandes villes (top 15)
//   public/sitemap-tier2.xml     — villes intermédiaires (~35)
//   public/sitemap-tier3.xml     — autres villes (~65)
//
// public/sitemap-events.xml is generated separately by the Supabase edge
// function `sitemap-events` (cron-driven) — this script never touches it.

import { writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import {
  SITE,
  getSeoRoutesForTier,
  type SeoRoute,
  type Tier,
} from '../supabase/functions/_shared/seo-routes.ts';

function esc(s: string): string {
  return s.replace(/[<>&'"]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' }[c]!));
}

function urlset(routes: SeoRoute[]): string {
  const body = routes
    .map(r => `  <url><loc>${esc(SITE + r.path)}</loc><changefreq>${r.changefreq}</changefreq><priority>${r.priority}</priority></url>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

function writeTier(tier: Tier): number {
  const routes = getSeoRoutesForTier(tier);
  writeFileSync(resolve(`public/sitemap-tier${tier}.xml`), urlset(routes));
  return routes.length;
}

function writeIndex(): void {
  const today = new Date().toISOString().slice(0, 10);
  const entries: string[] = [];
  for (const t of [1, 2, 3] as const) {
    entries.push(`  <sitemap><loc>${SITE}/sitemap-tier${t}.xml</loc><lastmod>${today}</lastmod></sitemap>`);
  }
  // Events sitemap is generated by an edge function — reference it only if
  // the file exists locally OR always advertise it (Google fetches it live).
  entries.push(`  <sitemap><loc>${SITE}/sitemap-events.xml</loc><lastmod>${today}</lastmod></sitemap>`);
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join('\n')}\n</sitemapindex>\n`;
  writeFileSync(resolve('public/sitemap.xml'), xml);
}

const counts = { t1: writeTier(1), t2: writeTier(2), t3: writeTier(3) };
writeIndex();

// Silence lint: "existsSync" imported for future use (deleting stale files).
void existsSync;

console.log(
  `sitemap.xml (index) + 3 tier files written — tier1: ${counts.t1}, tier2: ${counts.t2}, tier3: ${counts.t3} routes (total ${counts.t1 + counts.t2 + counts.t3})`,
);
