// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var search_events_default = defineTool({
  name: "search_events",
  title: "Rechercher des \xE9v\xE9nements",
  description: "Recherche les \xE9v\xE9nements PulseMap \xE0 venir (soir\xE9es, concerts, festivals, brocantes, sport, sorties). Filtres optionnels par ville, texte libre, type et fen\xEAtre de dates. Renvoie jusqu'\xE0 50 r\xE9sultats avec lieu, adresse, coordonn\xE9es GPS et lien billetterie.",
  inputSchema: {
    city: z.string().optional().describe("Ville fran\xE7aise (ex: 'Paris', 'Lyon'). Insensible \xE0 la casse."),
    query: z.string().optional().describe("Texte \xE0 chercher dans le nom, la description ou le lieu."),
    type: z.string().optional().describe("Type d'\xE9v\xE9nement (ex: 'concert', 'festival', 'soiree', 'brocante', 'sport')."),
    from: z.string().optional().describe("Date de d\xE9but ISO 8601. Par d\xE9faut : maintenant."),
    to: z.string().optional().describe("Date de fin ISO 8601. Par d\xE9faut : dans 90 jours."),
    limit: z.number().int().min(1).max(50).optional().describe("Nombre max de r\xE9sultats (d\xE9faut 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, query, type, from, to, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const nowIso = from ?? (/* @__PURE__ */ new Date()).toISOString();
    const untilIso = to ?? new Date(Date.now() + 90 * 864e5).toISOString();
    let q = supabase.from("cached_events").select("id,name,city,venue,address,lat,lng,start_time,end_time,description,image_url,ticket_url,price_range,type,source").gte("start_time", nowIso).lte("start_time", untilIso).order("start_time", { ascending: true }).limit(Math.min(limit ?? 20, 50));
    if (city) q = q.ilike("city", city);
    if (type) q = q.eq("type", type);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%,venue.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_default = defineTool2({
  name: "get_event",
  title: "D\xE9tails d'un \xE9v\xE9nement",
  description: "R\xE9cup\xE8re la fiche compl\xE8te d'un \xE9v\xE9nement PulseMap par son identifiant.",
  inputSchema: {
    event_id: z2.string().min(1).describe("Identifiant de l'\xE9v\xE9nement (ex: 'sg-paris-abc', 'icf-lyon-xxx').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("cached_events").select("*").eq("id", event_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "\xC9v\xE9nement introuvable." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/tonight-hotspots.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var tonight_hotspots_default = defineTool3({
  name: "tonight_hotspots",
  title: "Lieux chauds ce soir",
  description: "Retourne les \xE9v\xE9nements les plus populaires ce soir sur PulseMap (nombre de participants confirm\xE9s).",
  inputSchema: {
    limit: z3.number().int().min(1).max(30).optional().describe("Nombre max de spots (d\xE9faut 10, max 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.rpc("get_tonight_hotspots", { _limit: Math.min(limit ?? 10, 30) });
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { hotspots: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseFor(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_favorites_default = defineTool4({
  name: "list_my_favorites",
  title: "Mes favoris",
  description: "Liste les \xE9v\xE9nements marqu\xE9s comme favoris par l'utilisateur PulseMap connect\xE9.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { data, error } = await supabaseFor(ctx).from("event_favorites").select("event_id, event_name, event_city, event_date, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-favorite.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseFor2(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_favorite_default = defineTool5({
  name: "add_favorite",
  title: "Ajouter un favori",
  description: "Ajoute un \xE9v\xE9nement aux favoris de l'utilisateur PulseMap connect\xE9.",
  inputSchema: {
    event_id: z4.string().min(1),
    event_name: z4.string().min(1),
    event_city: z4.string().min(1),
    event_date: z4.string().optional().describe("Date ISO 8601 de l'\xE9v\xE9nement (facultatif).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, event_name, event_city, event_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { data, error } = await supabaseFor2(ctx).from("event_favorites").upsert(
      { user_id: ctx.getUserId(), event_id, event_name, event_city, event_date: event_date ?? null },
      { onConflict: "user_id,event_id" }
    ).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: `Favori ajout\xE9: ${event_name}` }],
      structuredContent: { favorite: data }
    };
  }
});

// src/lib/mcp/tools/mark-attendance.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseFor3(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var mark_attendance_default = defineTool6({
  name: "mark_attendance",
  title: "Je participe",
  description: "Indique que l'utilisateur connect\xE9 pr\xE9voit d'aller \xE0 un \xE9v\xE9nement PulseMap. Notifie les amis abonn\xE9s.",
  inputSchema: {
    event_id: z5.string().min(1),
    event_name: z5.string().min(1),
    event_city: z5.string().min(1),
    event_date: z5.string().optional().describe("Date ISO 8601 (facultatif).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, event_name, event_city, event_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { data, error } = await supabaseFor3(ctx).from("event_attendance").upsert(
      { user_id: ctx.getUserId(), event_id, event_name, event_city, event_date: event_date ?? null },
      { onConflict: "user_id,event_id" }
    ).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: `Participation confirm\xE9e: ${event_name}` }],
      structuredContent: { attendance: data }
    };
  }
});

// src/lib/mcp/tools/my-profile.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseFor4(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_profile_default = defineTool7({
  name: "my_profile",
  title: "Mon profil",
  description: "Renvoie le profil PulseMap de l'utilisateur connect\xE9 (pseudo, avatar, bio).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { data, error } = await supabaseFor4(ctx).from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ email: ctx.getUserEmail(), profile: data }, null, 2) }],
      structuredContent: { email: ctx.getUserEmail(), profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rhzojoyxldrllxroyyqt";
var mcp_default = defineMcp({
  name: "pulsemap-mcp",
  title: "PulseMap",
  version: "0.1.0",
  instructions: "Outils PulseMap : rechercher soir\xE9es, concerts, festivals, brocantes et sorties en France ; consulter les spots chauds de la soir\xE9e ; g\xE9rer favoris, participations et profil de l'utilisateur connect\xE9. Toujours r\xE9pondre en fran\xE7ais.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_events_default, get_event_default, tonight_hotspots_default, list_favorites_default, add_favorite_default, mark_attendance_default, my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
